theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs
title: Draumeister Dimd is trying out stuff here
description: I want to use this page to publish my Dungeon World hack Dimma & draugr.
